export default [
	{
		title: 'Nosdromy',
		subtitle: 'Official Music Video',
		date: 'October 4th 2023',
		youtubeId: 'HY8hrtxplac',
	},
	{
		title: 'Nosdromy',
		subtitle: 'Single Release',
		date: 'October 1st 2023',
		spotifyId: '50wrCHA8uo8DR1oqI7AUrC',
	},
	{
		title: 'ENEMY',
		subtitle: 'Official Music Video',
		date: 'September 12th 2023',
		youtubeId: 'lJpqPOwh5vM',
	},
	{
		title: 'ENEMY',
		subtitle: 'Single Release',
		date: 'September 8th 2023',
		spotifyId: '2W4mOZTNIDMBN2WlDvo6GM',
	},
	{
		title: "And Finally We Obviously Don't Know",
		subtitle: 'Single Release',
		date: 'February 4th 2023',
		spotifyId: '2Ov5qQkwjmVKLjKQFsTTZO',
	},
	{
		title: 'Space Dust And Starlight',
		subtitle: 'Album Release - Bandcamp',
		date: 'January 1st 2022',
		image: '/news/album-sdas-front.jpg',
		link: 'https://hurphendale.bandcamp.com/album/space-dust-and-starlight',
		linkText: 'Full Album available on Bandcamp',
	},
	{
		title: 'Space Dust And Starlight',
		subtitle: 'Album Release - Spotify',
		date: 'January 1st 2022',
		spotifyId: '0jF7umQynBPKo6D79fuLyf',
	},
	{
		title: 'Nautilus',
		subtitle: 'Official Music Video',
		date: 'December 31st 2021',
		youtubeId: 'F34CAOld72g',
	},
	{
		title: 'The Sylph Archive',
		subtitle: 'Official Music Video',
		date: 'December 30st 2021',
		youtubeId: '8xSKNknrBR0',
	},
	{
		title: '67 Space Dust And Starlight',
		subtitle: 'Official Music Video',
		date: 'December 29st 2021',
		youtubeId: '7iy5QsisZ5w',
	},
	{
		title: 'Album Preview: Space Dust And Starlight',
		subtitle: 'Official Release Date January 1st 2022 - Album Available For Pre-Order Now!',
		date: 'December 12th 2021',
		image: '/news/album-sdas-front.jpg',
		link: 'https://hurphendale.bandcamp.com/album/space-dust-and-starlight',
		linkText: 'Pre-order on Bandcamp',
	},
	{
		title: 'Cradled',
		subtitle: "Featured on SA02 'Resonance'",
		date: 'June 10th 2021',
		youtubeId: '7bLcp8Blkp4',
	},
	{
		title: "SA02: 'Resonance' Out Now",
		subtitle: 'Synthstrom Audible Compilation',
		date: 'May 30th 2021',
		image: '/news/resonance_cover.png',
		link: 'https://synthstrom.com/label',
		linkText: 'Purchase from Synthstrom Audible',
	},
	{
		title: "Track 'Cradled' Featured On SA02: 'Resonance'",
		subtitle: 'Synthstrom Audible Compilation',
		date: 'May 27th 2021',
		image: '/news/resonance_listening_party.jpg',
		link: 'https://synthstrom.com/whats-on-satv-in-may/',
	},
];
